### ISSUE TITLE
add_body_composition service ignores entity_id parameter

### ISSUE THREAD

**Issue by cornholio1234** [cyberjunky/home-assistant-garmin_connect#146]
We habe two garmin accounts for me and my wife.
I can add both accounts and HA is fetching the data for both, but updating the weight using the service will always end up in the first account linked.
I played around and found out that the entity_id is not relevant at all. I can just enter random characters and the first account is updated with the values. Any idea how to improve this behavior to allow multiple accounts linked?

```
service: garmin_connect.add_body_composition
data:
  weight: 57.1
  timestamp:  2024-03-07T11:47:00
  entity_id: abc
```

**Comment by cornholio1234** [comment]
#133 <- just saw this is just a more detailled duplicate of issue 133

**Comment by cornholio1234** [comment]
Just a reply on myself: I have added the integration twice - in different folders and adjusted some files so HASS sees now two integrations. This way I have two separate services I can call (one for each user). This is not nice but at all it is working. Maybe this is helpful for someone ...

**Comment by cornholio1234** [comment]
Hi Joss, just duplicate the folder. Then go through the files and adjust the name/domain like in my picture. It is only a couple of references. Restart hass and add another (now Garminconnect2) device with the secondary credentials

**Comment by JohnNeville** [comment]
I had this issue as well!

**Comment by borpin** [comment]
I'll add a 'me too'. This needs a unique device ID so the sensors created are unique to the device. Ideally, a name at setup time can be added so the sensors would be `sensor.garmin_connect_<name>_weight`.

**Comment by lug-gh** [comment]
@cornholio1234 Have you customised anything other than ‘domain’ and ‘name’? I did it as you wrote, but I can't add ‘Garmin Connect2’ as an integration, I get the error message ‘{’message‘: “Invalid handler specified”}’ in the Home Assistant, and no image is found for the integration.

![image](https://github.com/user-attachments/assets/e5925bb6-913b-44b6-a2db-ce893c4a78d2)

**Comment by cornholio1234** [comment]
Hi, looks like you found it - guess it was the one in const.py - i did not adjust the integration in the services.yaml but it seems to make no difference. (I have no icon for the second instance too).

**Comment by lug-gh** [comment]
@cornholio1234 

Unfortunately, I rejoiced too soon. Although I now have the garmin_connect2, the weight is uploaded to the first Garmin account of garmin_connect. I'm really wondering why this is the case, after all I explicitly specify garmin_connect2.

```
data:
  entity_id: sensor.weight_2
  weight: "{{trigger.to_state.state}}"
  timestamp: "{{ as_timestamp(now())  | timestamp_local}}"
  bmi: "{{ (trigger.to_state.state | float(0) / 1.86**2 )| round(1, default=0) }}"
action: garmin_connect2.add_body_composition
```
