### ISSUE TITLE
How does garmin_connect.add_blood_pressure action work?

### ISSUE THREAD

**Issue by Petucky** [cyberjunky/home-assistant-garmin_connect#239]
Hi,
I've noticed add_blood_pressure action, which I very much welcomed as I wanted to use HA to sync my data to garmin.
But I'm not sure how it works, if I don't see any blood pressure related entity?

When I run with example data below, I got error: This action requires field entity_id, which must be provided under 'data:'
```
action: garmin_connect.add_blood_pressure
data:
  systolic: 120
  diastolic: 80
  pulse: 60
  timestamp: 2023-12-30T07:34:00.000Z
  notes: Measured with Beurer BC54
```

When I added empty entity_id under data, it runs, but I don't see the value stored anywhere in garmin.

Thanks.

**Comment by cyberjunky** [comment]
It doesn't really matter which entity from the garmin connect integration you specify as long as it is linked to the account you want to update and is enabled.

I have updated the README with the examples.

You can use:
```
action: garmin_connect.add_blood_pressure
data:
  entity_id: sensor.min_heart_rate
  systolic: 120
  diastolic: 80
  pulse: 60
  timestamp: 2025-1-21T07:34:00.000Z
  notes: Measured with my device
```

The measurement shows up in the app under Health stats and Blood pressure, of course you need to look at the timestamp specified.
