### ISSUE TITLE
Syncing body composition

### ISSUE THREAD

**Issue by molofsso** [cyberjunky/home-assistant-garmin_connect#249]
Hi,

The feature to sync the weight from a scale (withings) to garmin connect works using the automation in the readme file: 

`alias: Send Weight to Garmin
description: ""
triggers:
  - entity_id:
      - sensor.withings_weight
    trigger: state
conditions:
  - condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.withings_weight
        above: 73
      - condition: numeric_state
        entity_id: sensor.withings_weight
        below: 78
actions:
  - data:
      entity_id: sensor.weight
      weight: "{{trigger.to_state.state}}"
      timestamp: "{{ as_timestamp(now())  | timestamp_local}}"
      bmi: >-
        {{ (trigger.to_state.state | float(0) / 1.82**2 )| round(1, default=0)
        }}
    action: garmin_connect.add_body_composition
mode: single`

I have 2 issues however:

**- How do I sync, with the same automation, the other parameters (bone mass, fat percentage etc.)?**
- When I go in developer tools, I can perform manually this action that works:

`action: garmin_connect.add_body_composition
data:
  entity_id: sensor.weight
  weight: 74.36
  bone_mass: 3.13
  muscle_mass: 59.64`

However, **if I add this line to it: ` body_fat: 15.0` it gives me this error:** "Failed to perform the action garmin_connect.add_body_composition. extra keys not allowed @ data['body_fat']. Got None"

So, ideally, I would like the automation to send weight, fat percentage, bone mass and muscle mass to garmin connect.

Thank you in advance and thank you for the great job!

**Comment by cyberjunky** [comment]
@molofsso where did you read `body_fat` is to be used? The action template shows the valid ones. 

![Image](https://github.com/user-attachments/assets/b9ace07e-8d1d-4743-9642-d843d4bc865f)

**Comment by molofsso** [comment]
Thank you for your quick reply. You're absolutely right.. sorry. I was using the entity in the garmin device and didn't check in the action template.

So how can you incorporate these two parameters (muscle mass and fat percentage) into the same automation?

Thank you in advance.

**Comment by cyberjunky** [comment]
By adding them just like bmi I guess?

```
actions:
  - service: garmin_connect.add_body_composition
    data:
      entity_id: sensor.weight
      weight: "{{ trigger.to_state.state }}"
      timestamp: "{{ as_timestamp(now()) | timestamp_local }}"
      bmi: "{{ (trigger.to_state.state | float(0) / 1.82**2) | round(1, default=0) }}"
      bone_mass: "{{ states('sensor.withings_bone_mass') | float }}"
      muscle_mass: "{{ states('sensor.withings_muscle_mass') | float }}"
```
