### ISSUE TITLE
Feature Request: post weight to Garmin Connect

### ISSUE THREAD

**Issue by 00pi** [cyberjunky/home-assistant-garmin_connect#74]
Hi,

as support for posting weight to Garmin Connect seem to be possible soon through cyberjunky/python-garminconnect#132 a HA [service call](https://www.home-assistant.io/docs/scripts/service-calls/) would be greatly appreciated.

My goal is to automatically sync my weight from my Mi Smartscale to Garmin Connect. The scale is working fine with [ble_monitor](https://github.com/custom-components/ble_monitor) and the data is available within HA.

There is a number of other projects providing such sync functionality outside of Home Assistant eg. https://github.com/lswiderski/mi-scale-exporter and https://github.com/RobertWojtowicz/miscale2garmin, but my preference would be to utilize my existing HA installation.

Thanks a lot,
Robert

**Comment by pejotigrek** [comment]
that sounds great, I was thinking about the same thing some time ago. would be great to see this in the integration

**Comment by Paxy** [comment]
+1 for this.
My project stopped working recently, and I can't fix it with the used approach (https://github.com/Paxy/php-garmin-uploadweight).

**Comment by Imperial-Guard** [comment]
+1

Currently I'm using the https://github.com/encodedLife/hassio_garmin_scale_sync but unfortunately BMI isn't reported within Garmin Connect.

**Comment by alexives** [comment]
Looks like this is supported using the [`add_weigh_in`](https://github.com/cyberjunky/python-garminconnect/blob/master/garminconnect/__init__.py#L323C9-L323C21) method from python-garminconnect now! Alternatly, could use [`add_body_composition`](https://github.com/cyberjunky/python-garminconnect/blob/master/garminconnect/__init__.py#L279) which also has support for a bunch of other body metrics like BMI ect. That might be preferable since it can handle _just_ weight, and the other metrics are optional.

**Comment by Imperial-Guard** [comment]
@alexives, this is great! I've tested your modifications and I can confirm that this is working perfectly.

**Comment by cyberjunky** [comment]
Added to 0.2.19! Thanks for requesting!

**Comment by 00pi** [comment]
@cyberjunky @alexives  Thank you very much for this functionality!!!

I set up an automation to pass my weight to Garmin Connect. Apparently Garmin Connect does calculate your BMI, when you enter your weight manually. When using the add_body_composition, BMI needs to be passed along.


```
alias: uiSendWeightToGarminConnect
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.my_weight
condition:
  - condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.my_weight
        above: 75
      - condition: numeric_state
        entity_id: sensor.my_weight
        below: 88
action:
  - service: garmin_connect.add_body_composition
    data:
      entity_id: sensor.garmin_connect_weight
      weight: "{{trigger.to_state.state}}"
      timestamp: "{{ as_timestamp(now())  | timestamp_local}}"
      bmi: >-
        {{ (trigger.to_state.state | float(0) / 1.86**2 )| round(1, default=0)
        }}
mode: single
```
