### ISSUE TITLE
VO2 max entity?

### ISSUE THREAD

**Issue by soggypete** [cyberjunky/home-assistant-garmin_connect#88]
Thank you for the hard work with the recent update pulling in all the equipment sensors. 

Is there a way to pull in the VO2 max score? Would be nice to track this on HA

**Comment by Valdorama** [comment]
Yeah this interesting is wonderful, and also looking for VO2 Max sensor.

**Comment by JossPer0** [comment]
Also here for this, would  be  great to rack

**Comment by Valdorama** [comment]
Any update on whether this can be implemented?

**Comment by cyberjunky** [comment]
I believe VO2Max is only updated during an activity.
I create a Last Activity sensor in version 0.2.29, so you should be able to create a VO2Max sensor like this: (untested)
```
sensor:
  - platform: template
    sensors:
      vo2max:
        friendly_name: "VO2Max"
        value_template: "{{ state_attr('sensor.last_activity', 'vO2MaxValue') }}"
```
